In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("heart_disease_data.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [4]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train)

[[ 0.35256528  0.70243936  0.9870291  ...  0.96222601  1.22723311
   1.12135917]
 [-0.31068598  0.70243936 -0.91982712 ...  0.96222601  0.25993479
  -0.45968761]
 [-0.08960223  0.70243936  0.9870291  ...  0.96222601 -0.70736353
   1.12135917]
 ...
 [ 0.13148153  0.70243936  1.94045721 ... -0.6557392  -0.70736353
   1.12135917]
 [-0.86339537  0.70243936  0.9870291  ...  0.96222601 -0.70736353
  -0.45968761]
 [ 0.35256528  0.70243936  0.03360099 ... -0.6557392  -0.70736353
  -0.45968761]]


In [8]:
print(X_test)

[[ 1.67906782  0.70243936 -0.91982712  0.77497606 -1.35743293 -0.42695628
   0.89174012 -1.04934923  1.38212026  1.22827842 -2.27370441 -0.70736353
   1.12135917]
 [ 1.01581655  0.70243936  1.94045721  2.22645762 -0.380682   -0.42695628
  -0.9825655   0.238927   -0.72352604 -0.4269261  -0.6557392  -0.70736353
   1.12135917]
 [ 0.46310716  0.70243936  1.94045721  2.22645762  0.74350304 -0.42695628
  -0.9825655   0.41069717 -0.72352604 -0.757967   -0.6557392  -0.70736353
   1.12135917]
 [ 0.57364904  0.70243936 -0.91982712 -0.38620919  0.19062515 -0.42695628
  -0.9825655  -0.36226857  1.38212026  1.39379887 -0.6557392   0.25993479
   1.12135917]
 [ 0.79473279  0.70243936  0.9870291  -0.09591288 -0.30696495 -0.42695628
   0.89174012 -0.14755587 -0.72352604  0.56619661 -0.6557392   2.19453143
   1.12135917]
 [-0.75285349  0.70243936 -0.91982712 -0.44426845  0.48549336 -0.42695628
  -0.9825655   0.71129496 -0.72352604 -0.50968632 -0.6557392  -0.70736353
   1.12135917]
 [-1.63718851  0.70243

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24  9]
 [ 6 37]]


0.8026315789473685

In [11]:
classifier.predict([[60,0,0,140,268,0,0,160,0,3.6,0,2,2]])

array([0])